### ISSUE TITLE
Invalid `toJson()` impl (freezed v2.4.6)?

### ISSUE THREAD

**Issue by KeidsID** [rrousselGit/freezed#1037]
## Describe the bug

The generated `toJson` for list of another freezed class is return the actual
object instead `Map<String, dynamic>`.

```dart
// generated to json impl

Map<String, dynamic> _$$RawBudgetImplToJson(_$RawBudgetImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'details': instance.details,
      'created_at': instance.createdAt.toIso8601String(),

      // instance of `List<RawBudgetData>` which is freezed class
      // expected: `instance.budgets.map((e) => e.toJson()).toList()`,
      'budgets': instance.budgets,
    };
```

I try to override the `toJson` but it also did not work.

````dart
@override
Map<String, dynamic> toJson() {
  return {
    'id': id,
    'details': details,
    'created_at': createdAt.toIso8601String(),
    'budgets': budgets.map((e) => e.toJson()).toList(),
  };
}

Map<String, dynamic> toFirestoreMap() {
  // `toJson` still return the actual object for "budgets" key.
  // ```
  // {
  //   "id": "id",
  //   "details": "details",
  //   "created_at": "2022-01-01T00:00:00.000Z",
  //   "budgets": ["RawBudgetData()"],
  // }
  // ```
  return toJson().map((k, v) {
    return MapEntry(
      k,
      k != 'created_at' ? v : Timestamp.fromDate(DateTime.parse(v)),
    );
  });
}
````

## To Reproduce

pubspec.yaml

```yaml
environment:
  sdk: ^3.2.3
  flutter: ^3.16.5

dependencies:
  flutter:
    sdk: flutter

  # firebase
  cloud_firestore: ^4.14.0
  # firebase_core: ^2.24.2 # just need Timestamp from `cloud_firestore`

  # annotation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^3.0.1

  # code builder/generator
  build_runner: ^2.4.7
  build_verify: ^3.1.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1
```

build.yaml

```yaml
targets:
  $default:
    builders:
      freezed:
        options:
          to_json: true
          explicit_to_json: true
          copy_with: false
          equal: false
```

Freezed classes (save as `raw_budget.dart`):

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'raw_budget.freezed.dart';
part 'raw_budget.g.dart';

@freezed
class RawBudget with _$RawBudget {
  const factory RawBudget({
    required String id,
    required String details,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    required List<RawBudgetData> budgets,
  }) = _RawBudget;


  factory RawBudget.fromJson(Map<String, dynamic> json) =>
      _$RawBudgetFromJson(json);

  @override
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'details': details,
      'created_at': createdAt.toIso8601String(),
      'budgets': budgets.map((e) => e.toJson()).toList(),
    };
  }

  const RawBudget._();

  Map<String, dynamic> toFirestoreMap() {
    return toJson().map((k, v) {
      return MapEntry(
        k,
        k != 'created_at' ? v : Timestamp.fromDate(DateTime.parse(v)),
      );
    });
  }
}

@freezed
class RawBudgetData with _$RawBudgetData {
  const factory RawBudgetData({
    required String id,
    required String name,
    RawBudgetDataValue? value,
  }) = _RawBudgetData;

  factory RawBudgetData.fromJson(Map<String, dynamic> json) =>
      _$RawBudgetDataFromJson(json);

  @override
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'value': value?.toJson(),
    };
  }

  // const RawBudgetData._();
}

@freezed
class RawBudgetDataValue with _$RawBudgetDataValue {
  const factory RawBudgetDataValue({
    required String unit,
    required double volume,
    required double price,
  }) = _RawBudgetDataValue;

  factory RawBudgetDataValue.fromJson(Map<String, dynamic> json) =>
      _$RawBudgetDataValueFromJson(json);

  // const RawBudgetDataValue._();
}

```

## Expected behavior

Correct implementation of `toJson` like described on
[Describe the bug](#describe-the-bug) section.
