### ISSUE TITLE
Freezed 2.5.3 doesn't work with latest stable Flutter

### ISSUE THREAD

**Issue by fernando-s97** [rrousselGit/freezed#1098]
**Describe the bug**
Freezed 2.5.3 doesn't work with Flutter 3.22.2. When I add the dependencies and run `flutter pub get`, I get 

```
Note: meta is pinned to version 1.12.0 by flutter from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because analyzer >=6.5.1 depends on meta ^1.15.0 and analyzer >=6.5.0 <6.5.1 depends on meta ^1.14.0, analyzer >=6.5.0 requires meta ^1.14.0.
And because freezed >=2.5.3 <3.0.0-0.0.dev depends on analyzer ^6.5.0 and every version of flutter from sdk depends on meta 1.12.0, freezed >=2.5.3 <3.0.0-0.0.dev is incompatible with flutter from sdk.
So, because gradu_go depends on both flutter from sdk and freezed ^2.5.3, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on freezed: flutter pub add dev:freezed:^2.5.2
```

**To Reproduce**

Create a project with Flutter 3.22.2 and run

```
flutter pub add freezed_annotation
flutter pub add dev:build_runner
flutter pub add dev:freezed
flutter pub add json_annotation
flutter pub add dev:json_serializable
```

Note: I'm assuming the latest freezed version is 2.5.3

**Expected behavior**
Dependencies added normally

That's my pubspec

```yaml
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  url_launcher: ^6.3.0
  transparent_image: ^2.0.1
  intl: ^0.19.0
  card_swiper: ^3.0.1
  json_annotation: ^4.9.0
  injectable: ^2.4.2
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1

dependency_overrides:
  collection: ^1.19.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  lint: ^2.3.0

flutter:
  uses-material-design: true
```
