### ISSUE TITLE
toString override not working

### ISSUE THREAD

**Issue by johnnyggalt** [rrousselGit/freezed#1120]
**Describe the bug**
Overriding `toString` does not work. I feel like I must be doing something incredibly stupid, but have boiled this down to simplest thing that should work, and it doesn't.

**To Reproduce**

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'repro.freezed.dart';

@freezed
class Repro with _$Repro {
  const factory Repro({required int foo}) = _Repro;

  @override
  String toString() => 'My custom toString';
}

void doRepro() {
  const repro = Repro(foo: 42);

  // "Instance of '_$ReproImpl'"
  final reproToString = repro.toString();
}
```

**Expected behavior**
My `toString` implementation should be invoked, not that of the `_$ReproImpl` type. Even the IDE agrees it should be invoking my implementation because go-to-definition jumps there, but nope.

This is using latest:

```yaml
dependencies:
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
```
