### ISSUE TITLE
The class doesn't have a concrete implementation of the super-invoked member 'debugFillProperties'.

### ISSUE THREAD

**Issue by karakorumguy** [rrousselGit/freezed#1163]
**Describe the bug**

Importing foundation.dart cause the following error.
The class doesn't have a concrete implementation of the super-invoked member 'debugFillProperties'.

If we remove the foundation import, no error.

**To Reproduce**

```
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'person.freezed.dart';
part 'person.g.dart';

@freezed
abstract class Person with _$Person {
  const factory Person({
    required String firstName,
    required String lastName,
    required int age,
  }) = _Person;

  factory Person.fromJson(Map<String, Object?> json) => _$PersonFromJson(json);
}
```

dependencies and dev dependencies
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.4
```
<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

**Expected behavior**

No error when importing foundation.dart
