### ISSUE TITLE
Deep copy from a separate library/file in freezed 3.0.0 doesn't generate

### ISSUE THREAD

**Issue by D-James-GH** [rrousselGit/freezed#1164]
**Describe the bug**
Freezed deep copy doesn't seem to be generated if the nested freezed object is in a different library/file. In freezed 3.0.0.

**To Reproduce**
 
Pubspec: 
```yaml
name: freezed_issue
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.4

```

Library File: 
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part "object_three.freezed.dart";
part "object_three.g.dart";

@freezed
abstract class DifferentLibrary with _$DifferentLibrary {
  const factory DifferentLibrary({required String? value}) = _DifferentLibrary;
  factory DifferentLibrary.fromJson(Map<String, dynamic> json) =>
      _$DifferentLibraryFromJson(json);
}

```

Main file:
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

import 'object_three.dart';

part "freezed_issue.freezed.dart";
part "freezed_issue.g.dart";

@freezed
abstract class SameLibrary with _$SameLibrary {
  const factory SameLibrary({required String? value}) = _SameLibrary;
  factory SameLibrary.fromJson(Map<String, dynamic> json) =>
      _$SameLibraryFromJson(json);
}

@freezed
abstract class ObjectOne with _$ObjectOne {
  const factory ObjectOne({
    required SameLibrary sameLibrary,
    required DifferentLibrary differentLibrary,
  }) = _ObjectOne;
  factory ObjectOne.fromJson(Map<String, dynamic> json) =>
      _$ObjectOneFromJson(json);
}

main() {
  final objectOne = ObjectOne(
    sameLibrary: SameLibrary(value: "value"),
    differentLibrary: DifferentLibrary(value: "value"),
  );
/// Works as expected
  final x = objectOne.copyWith.sameLibrary(value: "new value");
/// ERROR: The method 'differentLibrary' isn't defined for the type '$ObjectOneCopyWith'. 
  final error = objectOne.copyWith.differentLibrary(value: "new value");
}

```

**Expected behavior**
The `differentLibrary` deep copy is generated even though it is part of a different library/file. 

I can see there is a deep copy 2 test so my error could be something I missed in the upgrade. But I couldn't find anything in the breaking changes.
