### ISSUE TITLE
Files not generated with freezed 3.0.0-0.0.dev and Hive

### ISSUE THREAD

**Issue by liubou-s-inno** [rrousselGit/freezed#1206]
**Describe the bug**
We are using Hive in our project, because of that the latest resolvable versions of libraries are following:
```yaml
dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  hive_generator: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.0
``` 
With these versions, running `dart run build_runner build` does not generate `.freezed.dart` and `.g.dart` files.

**To Reproduce**

1. Use the dependencies provided above in `pubspec.yaml`.
2. Create a simple `person.dart` file:
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'person.freezed.dart';
part 'person.g.dart';

@freezed
abstract class Person with _$Person {
  const factory Person({required String firstName, required String lastName, required int age}) = _Person;

  factory Person.fromJson(Map<String, Object?> json) => _$PersonFromJson(json);
}
``` 
3. Run `flutter pub get` and  `dart run build_runner build --delete-conflicting-outputs`.

**Expected behavior**
`person.freezed.dart` and `person.g.dart` generated.

**Environment**
Flutter 3.29.0 • Dart 3.7.0
