### ISSUE TITLE
Build error with generic freezed model in latest version

### ISSUE THREAD

**Issue by lehoangkhang4869** [rrousselGit/freezed#1249]
**Describe the bug**
When building a generic model using `freezed`, which previously worked in older versions, the latest version causes a build-time error. The same model has been used reliably for a long time, but now fails after updating to the latest versions of the relevant packages.

**To Reproduce**
Use the following model code:

```dart
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 't_data.freezed.dart';

@Freezed()
abstract class TData<T> with _$TData {
  const factory TData({required T t}) = _TData;
}
```

Then run:

```bash
flutter pub run build_runner build
```

You will get the error:

```
The argument type 'TData<dynamic>' can't be assigned to the parameter type 'TData<T>'.
```

This behavior **did not occur in older versions**, and the model was working as expected without any issues before.

**Expected behavior**
The code should compile successfully. The generic type `T` should be correctly inferred and respected as it was in prior versions of `freezed`.

**Environment:**

```yaml
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  flutter_lints: ^5.0.0
```

Please confirm whether this is a bug or an intentional syntax change in the latest version of `freezed`.
