### ISSUE TITLE
freezed  doesn't call .toJson() on nested freezed model (inside *.g.dart)

### ISSUE THREAD

**Issue by devnoaman** [rrousselGit/freezed#1262]
**Description:**

When using `freezed` , if I define a model like this:

```dart
@freezed
abstract class ModelA with _$ModelA {
  const factory ModelA({required double latitude, required double longitude}) = _ModelA;

  factory ModelA.fromJson(Map<String, dynamic> json) => _$ModelAFromJson(json);
}

@freezed
abstract class ModelB with _$ModelB {
  const factory ModelB({required ModelA modelA}) = _ModelB;

  factory ModelB.fromJson(Map<String, dynamic> json) => _$ModelBFromJson(json);
}
```

The generated `ModelB.toJson()` just returns the `modelA` instance instead of calling `modelA.toJson()`:

```dart
Map<String, dynamic> _$ModelBToJson(_ModelB instance) => <String, dynamic>{
  'modelA': instance.modelA, // This is wrong
};
```

Expected:

```dart
'modelA': instance.modelA.toJson(),
```

It works if I manually add `@JsonKey(toJson: convertToJson)`, but it would be helpful if this were handled automatically.

---

pubspec.yaml
```yaml

environment:
  sdk: ^3.8.1

dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.5.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5

```
