### ISSUE TITLE
No generated json_serializable file

### ISSUE THREAD

**Issue by kaciula** [rrousselGit/freezed#133]
Take the following file.

```
part 'city_response.freezed.dart';
part 'city_response.g.dart';

@freezed
abstract class CityResponse with _$CityResponse {
  factory CityResponse(
    @JsonKey(name: 'long_name') String longName,
    @JsonKey(name: 'short_name') String shortName,
    List<String> types,
  ) = _CityResponse;

  factory CityResponse.fromJson(Map<String, dynamic> json) =>
      _$CityResponseFromJson(json);
}
```

It does not generate the city_response.g.dart needed for json_serializable.

**Comment by rrousselGit** [comment]
It's likely caused by an outdated build_runner. Make sure you use the v latest version

**Comment by kaciula** [comment]
@rrousselGit I've updated to the latest and the issue is still there. Tried several times.

```
dev_dependencies:
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  freezed: ^0.10.4
```

**Comment by rrousselGit** [comment]
I can't reproduce the problem. It works for me

**Comment by pblinux** [comment]
Hi.

I'm having the same problem, using the sample code:

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';
part 'model.g.dart';

@freezed
abstract class Model with _$Model {
  factory Model.first(String a) = First;
  factory Model.second(int b, bool c) = Second;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```
The `model.g.dart` it is not generating.

 All packages are updated to the latest version:

```
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  freezed: ^0.10.7
  json_serializable: ^3.3.0
```
