### ISSUE TITLE
g.dart not generating.

### ISSUE THREAD

**Issue by pblinux** [rrousselGit/freezed#160]
Hi.

I'm having the same problem of #133, the `model.g.dart` it is not generating. 

Using the sample code:

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';
part 'model.g.dart';

@freezed
abstract class Model with _$Model {
  factory Model.first(String a) = First;
  factory Model.second(int b, bool c) = Second;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```

All packages are updated to the latest version:
```
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  freezed: ^0.10.7
  json_serializable: ^3.3.0
```

**Comment by malcolmpl** [comment]
@pblinux Delete pubspec.lock file then run 'flutter pub get' and then run again build_runner.

**Comment by pblinux** [comment]
Thank you @malcolmpl, that was weird but solved it.

**Comment by huangwei4478** [comment]
> @pblinux Delete pubspec.lock file then run 'flutter pub get' and then run again build_runner.

Solved my issue, too!

**Comment by thenifemi** [comment]
Didn't work for me and I am about to lose my mind😃

**Comment by lukepighetti** [comment]
`onboarding_firebase_models.g.dart` is not generating

```yaml 
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.1
  freezed: ^0.12.7

```
 
```yaml
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:vgl/onboarding/onboarding_enums.dart';

part 'onboarding_firebase_models.freezed.dart';
part 'onboarding_firebase_models.g.dart';

@freezed
abstract class FirebaseUserInfo with _$FirebaseUserInfo {
  factory FirebaseUserInfo({
    /// The onboarding name we selected
    String displayName,

    /// The pronouns of the user
    IdentityPronoun pronouns,

    /// The handedness of the user.
    AccessibilityHandedness handedness,

    /// The URL of the avatar we uploaded
    String avatarUrl,
  }) = _FirebaseUserInfo;

  factory FirebaseUserInfo.fromJson(Map<String, dynamic> json) =>
      _$FirebaseUserInfoFromJson(json);
}

```
