### ISSUE TITLE
Make freezed compatible with expression body lint rule

### ISSUE THREAD

**Issue by Solido** [rrousselGit/freezed#186]
Hello Remi,

I use the `prefer_expression_function_bodies` extensively but the linter return a consequent numbers of warns from .freezed files which kinda defeat the lint.

Would it be possible to update the generated file to make them compatible ?

I see no side effect for the majority of user ignoring this rules.

Thank you !

**Comment by rrousselGit** [comment]
Updating the generated code to follow every lint ever is a lot of work

I'd recommend you to instead exclude generated files from the linter

```yaml
# analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
```
