### ISSUE TITLE
Sort unnamed constructor declarations first

### ISSUE THREAD

**Issue by sarbagyastha** [rrousselGit/freezed#189]
![image](https://user-images.githubusercontent.com/9782008/83394420-4874b580-a418-11ea-8406-a54dfdaaf424.png)

Request to either reorder the constructor or add an ignore for the lint.

Thank you.

**Comment by SunlightBro** [comment]
Please follow the official dart guildline on how to exclude generated files:
https://dart.dev/guides/language/analysis-options#excluding-code-from-analysis

```YAML
# analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
```
