### ISSUE TITLE
FromJson returning null value

### ISSUE THREAD

**Issue by zgramming** [rrousselGit/freezed#235]
I have class and generate **toJson & fromJson** , i have problem generate json from API to Object. I have return json from API like this : 

### Json 

```
{
    "status": "ok",
    "message": "Data utang sebagai pembertang ",
    "data": [
        {
            "id_utang": "124",
            "pembertang": {
                "id_user": "111395227810958186033",
                "name_user": "Zeffry Reynando",
                "email_user": "zeffry.reynando@gmail.com",
                "image_user": "https://lh3.googleusercontent.com/a-/AOh14GiIqxTHoBba1eooOh9TmsBkVFb9GQzz3zByx8IIKA=s96-c",
                "token_fcm": "dk5s7T9ARrmSVHl1e4T1zc:APA91bFUEyOcwjLCZEuW525bxn9forOPVxvc2IGlc2fD90rf0znghnuGtJWuWnaGIs_1Zw8xBfuJ5B5ggj1zut4fenzJHqD7PgCrHbiHBu0vFqcyVZw9zHfiYDN9kBSUj2ekouIu99Su",
                "created_date": "2020-07-26 12:04:33"
            },
            "pengutang": {
                "id_user": "105164526876912904397",
                "name_user": "Akun Testing",
                "email_user": "akun.testing4444@gmail.com",
                "image_user": "https://lh5.googleusercontent.com/-p46wtaUFEQA/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucn5itDrBrYoZfLoCRfqHzkLo-FgIA/s96-c/photo.jpg",
                "token_fcm": "eqzBVVRAQOqRBKdyi_oQHk:APA91bHOXO0DKTkDVplUte_-itvcPNohcpRCIYFmgSgGn6o9xobk6kkoiibIWP_v5uFYe7EXHyH0NAJvzQIB9XSViQGYn7OIGgW26hzAY4-H3jhbCyB0t9bCNx2WzYF9nT5vFiYutBfb",
                "created_date": "2020-07-25 14:10:46"
            },
            "total_utang": "150000",
            "sisa_utang": "150000",
            "tgl_kembali": "2020-10-10 00:00:00",
            "status": "1",
            "keterangan": "kepo lu",
            "selfie": "3ed425415636e023107b27b4f2d33844.jpg",
            "ttd": "askdj ksajd lasjdlksajd jsadkjsakd",
            "created_date": "2020-07-26 09:25:56"
        },
    ]
}
``` 
But when i generate that json with `final listUtang = list.map((e) => UtangModel.fromJson(e)).toList();` . I have return null on  that.

### After generate 

```
List After Compiled UtangModel(idUtang: null, pembertang: UserGoogleModel(idUser: null, nameUser: null, emailUser: null, imageUser: null, tokenFcm: null, createdDate: null), pengutang: UserGoogleModel(idUser: null, nameUser: null, emailUser: null, imageUser: null, tokenFcm: null, createdDate: null), totalUtang: null, sisaUtang: null, tglKembali: null, status: 1, keterangan: kepo lu, selfie: 3ed425415636e023107b27b4f2d33844.jpg, ttd: askdj ksajd lasjdlksajd jsadkjsakd, createdDate: null)
```

### UtangModel 

```

@freezed
abstract class UtangModel with _$UtangModel {
  const factory UtangModel(
      {String idUtang,
      UserGoogleModel pembertang,
      UserGoogleModel pengutang,
      String totalUtang,
      String sisaUtang,
      DateTime tglKembali,
      String status,
      String keterangan,
      String selfie,
      String ttd,
      DateTime createdDate}) = _UtangModel;
  factory UtangModel.fromJson(Map<String, dynamic> json) => _$UtangModelFromJson(json);
}

```

### UserModel

```
@freezed
abstract class UserGoogleModel with _$UserGoogleModel {
  const factory UserGoogleModel(
      {String idUser,
      String nameUser,
      String emailUser,
      String imageUser,
      String tokenFcm,
      DateTime createdDate}) = _UserGoogleModel;
  factory UserGoogleModel.fromJson(Map<String, dynamic> json) => _$UserGoogleModelFromJson(json);
}

```

# Pubspec.yaml

```
dependencies:
  flutter:
    sdk: flutter
  # Function scan and make QR Code
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  # Onboarding Screen
  introduction_screen: ^1.0.9
  # State Management
  flutter_riverpod: ^0.5.1
  # Login With Google
  google_sign_in: ^4.5.1
  # Push Firebase and Local Notification
  flutter_local_notifications: ^1.4.4+2
  firebase_messaging: ^6.0.16
  # Signature
  flutter_signature_view: ^1.1.1
  freezed_annotation: ^0.11.0
  json_annotation: ^3.0.1

  firebase_crashlytics: ^0.1.3+3
  google_nav_bar: ^2.2.0
  shared_preferences: ^0.5.8
  image_picker: ^0.6.7+4
  flutter_datetime_picker: ^1.3.8
  http: ^0.12.2
  grouped_list: ^3.3.0
  global_template:
    path: global_template

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.7.5
  build_runner: ^1.10.0
  freezed: ^0.11.4
  json_serializable: ^3.3.0
```
