### ISSUE TITLE
Depends on 0.39.4 analyzer and I need 0.40.0

### ISSUE THREAD

**Issue by gedu** [rrousselGit/freezed#277]
**Describe the bug**
Tried to set up hive as my local DB lib and got this error, and won't like to downgrade too much the hive lib version:

```
Because freezed >=0.1.2 <0.11.6 depends on analyzer ^0.39.4 and hive_generator >=0.8.0 depends on analyzer >=0.40.0 <2.0.0, freezed >=0.1.2 <0.11.6 is incompatible with hive_generator >=0.8.0.

So, because APP_NAME depend on both hive_generator 0.8.1 and freezed 0.1.2, version solving failed.
pub get failed (1; So, because APP_NAME depend on both hive_generator 0.8.1 and freezed 0.1.2, version solving failed.)

```
**To Reproduce**
Installed:
```
dependencies:
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

dev_dependencies:
  hive_generator: ^0.8.1
  build_runner: ^1.10.3
```

**Expected behavior**
If I explicitly set analyzer: 0.40.0 freezed should work
