### ISSUE TITLE
*.g.dart and fromJson/toJson are not generated after updating to Flutter 1.22.1

### ISSUE THREAD

**Issue by MasterHiei** [rrousselGit/freezed#284]
**Describe the bug**
build_runner will remove all generated `*.g.dart` files and `fromJson/toJson` code in `*.freezed.dart` but not regenerate after updating to Flutter 1.22.1.
I tried to discard all file changes but they are not fixed. It works fine on Flutter 1.22.0.

This is my `pubspec.yaml` file:
```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_review: ^2.0.1
  badges: ^1.1.3
  bloc: ^6.0.3
  bubble: ^1.1.9+1
  cached_network_image: ^2.3.2+1
  camera: ^0.5.8+8
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  extended_nested_scroll_view: ^1.0.1
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.2
  firebase_crashlytics: ^0.2.1+1
  fluro: ^1.6.3
  flutter_bloc: ^6.0.6
  flutter_cache_manager: ^1.4.2
  flutter_screenutil: ^3.1.1
  font_awesome_flutter: ^8.10.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  image_cropper: ^1.3.1
  image_gallery_saver: '^1.6.0'
  image_picker: ^0.6.7+11
  injectable: ^1.0.5
  intl: ^0.16.1
  json_annotation: ^3.1.0
  kt_dart: ^0.8.0
  logger: ^0.9.4
  oktoast: ^2.3.2
  package_info: ^0.4.3
  path: ^1.7.0
  percent_indicator: ^2.1.7+4
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.2
  pull_to_refresh: ^1.6.2
  shared_preferences: ^0.5.12
  sqflite: ^1.3.1+1
  timeago: ^2.0.27
  url_launcher: ^5.7.2
  uuid: ^2.2.2
  webview_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.3
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.0
  mockito: ^4.1.1
  pedantic: ^1.9.2
```

**To Reproduce**
I have no idea what happened on my code. I just updated Flutter SDK and some packages like build_runner to the latest version and run `flutter pub run build_runner watch --delete-conflicting-outputs` as usual.

**Expected behavior**
Resolve this problem.

**Comment by MasterHiei** [comment]
update:
Flutter SDK looks like irrelevant. When I downgrade the SDK version it still is not working.

**Comment by rrousselGit** [comment]
What do you mean by they stop generating? Do you have an error?

**Comment by MasterHiei** [comment]
When I run `flutter pub run build_runner watch --delete-conflicting-outputs`, all old `*.g.dart` files and `fromJson/toJson` methods like below will be deleted, and will be not regenerated.
```dart
Model _$ModelFromJson(Map<String, dynamic> json) {
  return _Model.fromJson(json);
}
```
No error occurred of course.

**Comment by MasterHiei** [comment]
That's what I did today:
1. update Flutter SDK to 1.22.1
2. update some packages
3. run `flutter clean` & `flutter pub upgrade`
4. run `flutter pub run build_runner watch --delete-conflicting-outputs`
5. issue happened
6. discard all file changes and try step.3~4 again
7. still happened
8. downgrade Flutter SDK to 1.22.0 and try step.3~4 again
9. still happened

**Comment by James-A-White** [comment]
I'm also seeing this problem. My workaround was to downgrade Flutter, run flutter pub run build_runner watch --delete-conflicting-outputs and then upgrade Flutter.  It's not ideal, but should keep development going until a fix has been applied to Freezed.

**Comment by MasterHiei** [comment]
@James-A-White Thanks for sharing. Well, it's not the best approach but seems not bad. build_runner will cache the previous snapshot unless you clean it up. I guess that's why this problem did not happened when I upgraded to the Flutter 1.22.0.

**Comment by rrousselGit** [comment]
> That's what I did today:
> 
> 1. update Flutter SDK to 1.22.1
> 2. update some packages
> 3. run `flutter clean` & `flutter pub upgrade`
> 4. run `flutter pub run build_runner watch --delete-conflicting-outputs`
> 5. issue happened
> 6. discard all file changes and try step.3~4 again
> 7. still happened
> 8. downgrade Flutter SDK to 1.22.0 and try step.3~4 again
> 9. still happened

I tried that locally and it works for me
The CI also does that and pass
So I'm not sure how to reproduce the issue

**Comment by MasterHiei** [comment]
@rrousselGit Thank you. That's weird but I'll try to find out more information.

**Comment by James-A-White** [comment]
Not that it is super helpful, but it will generate the proper files for most of my data classes, but there are a few that just don't work. I've copied one below for your entertainment pleasure.

`// Copyright © 2020, InnoVet Europe
// All rights reserved

// package imports
import 'package:freezed_annotation/freezed_annotation.dart';

part 'place_status_request.g.dart';
part 'place_status_request.freezed.dart';

@freezed
abstract class PlaceStatusRequest with _$PlaceStatusRequest {
  const factory PlaceStatusRequest({
    String staffId,
    String accessToken,
    String tapPointId,
    String roomId,
    String floorplanId,
    String buildingId,
    String facilityId,
    String functionId,
    String functionCode,
    String functionStatusId,
    String functionStatusCode,
    String data,
    String topPriorityParams,
    String bottomPriorityParams,
  }) = _PlaceStatusRequest;

  factory PlaceStatusRequest.fromJson(Map<String, dynamic> json) {
    return _$PlaceStatusRequestFromJson(json);
  }
}
`

**Comment by MasterHiei** [comment]
freezed works fine on `Flutter 1.20.4, build_runner 1.10.1, freezed 0.12.1`. All files and methods are generated completely.

**Comment by MasterHiei** [comment]
@rrousselGit Hi👋, I reproduced this issue follow the steps below:
1. create a new flutter project(named `freezed_test`,  `Flutter: 1.22.1`)
2. modify `pubspec.yaml` to 
```yaml
name: freezed_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.3
  freezed: ^0.12.2
  json_serializable: ^3.5.0

flutter:
  uses-material-design: true
```
3. add a new file named `test_model.dart` like
```dart:test_model.dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test_model.freezed.dart';
part 'test_model.g.dart';

@freezed
abstract class TestModel with _$TestModel {
  const factory TestModel({
    String id,
    @JsonKey(name: 'test_name') String testName,
  }) = _TestModel;

  factory TestModel.fromJson(Map<String, dynamic> json) {
    return _$TestModelFromJson(json);
  }
}
```
4. run `flutter pub upgrade`
5. run `flutter pub run build_runner watch --delete-conflicting-outputs`

And then only `test_model.freezed.dart` will be generated without `test_model.g.dart` and `fromJson/toJson`.
