### ISSUE TITLE
Support any_map from json-serializable

### ISSUE THREAD

**Issue by volskaya** [rrousselGit/freezed#292]
**Describe the bug**
Json methods, generated by freezed, ignore json_serializable's `any_map`, in `build.yaml`, as well as manually setting true with the decorator `JsonSerializable()`.

The generated methods in `.g.dart` properly generate `Map json`, only `.freezed.dart` versions still generate `Map<String, dynamic> json`, causing a type cast error.

As per docs, I assume it's intended to work, "[If you want to define some custom json_serializable flags for all the classes (e.g. explicit_to_json or any_map) you can do it via build.yaml file as described here](https://github.com/rrousselGit/freezed#fromjson---classes-with-multiple-constructors)".

**To Reproduce**

```dart
@freezed
abstract class Example with _$Example {
  @JsonSerializable(anyMap: true)
  const factory Example({
    @JsonKey() String something,
  }) = _Example;

  factory Example.fromJson(Map json) => _$ExampleFromJson(json);
}
```

###### build.yaml
```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: true
          include_if_null: true
          nullable: true
```

**Expected behavior**
The generated function should generate `Map json`, but instead still generates `Map<String, dynamic> json`.

```dart
Example _$ExampleFromJson(Map<String, dynamic> json) {
  return _Example.fromJson(json);
}
```

The `json_serializable` generated helper functions are all fine.
```dart
_$_Example _$_$_ExampleFromJson(Map json) {
  return _$_Example(
    something: json['something'] as String,
  );
}

Map<String, dynamic> _$_$_ExampleToJson(_$_Example instance) =>
    <String, dynamic>{
      'something': instance.something,
    };
```
