### ISSUE TITLE
0.12.3 File Generation really slow for deep-copy spread across multiple files

### ISSUE THREAD

**Issue by Peng-Qian** [rrousselGit/freezed#312]
#### Problem
After the update of Freezed 0.12.3, it will be stuck in the file generation process.

it will randomly stop working somewhere...
![Screen Shot 2020-11-22 at 7 35 40 PM](https://user-images.githubusercontent.com/37643086/99896924-eb3c2b80-2cf9-11eb-8680-6a254fffda4e.png)

#### Dependencies 
```
dev_dependencies:
  build_runner: ^1.10.4
  freezed: ^0.12.3

dependency_overrides:
  analyzer: 0.40.4
```

#### Work Around
```
dev_dependencies:
  freezed: 0.12.2
```
