### ISSUE TITLE
type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast

### ISSUE THREAD

**Issue by kenNg1** [rrousselGit/freezed#383]
Great work on this library it's saving me a lot of time.

I'm experiencing an issue with converting a List<Activity> type from JSON. I get the error `type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast` but I cannot figure out what the issue is from the documentation or previous issues raised. Can you please tell me if I'm doing something wrong?

```
// factory class

@freezed
class Activity with _$Activity {
  @JsonSerializable()
  const factory Activity({
    required String title,
    String? category,
  }) = _Activity;
  factory Activity.fromJson(Map<String, dynamic> json) => _$ActivityFromJson(json);
}

@freezed
class Activities with _$Activities {
  @JsonSerializable()
  const factory Activities({
    required List<Activity> items,
  }) = _Activities;
  factory Activities.fromJson(Map<String, dynamic> json) => _$ActivitiesFromJson(json);
}

// usage of class

const json = {
  "activities": {
    "items": [
      "{title=Dinner, category=FOOD}",
      "{title=Drinks, category=FOOD}",
      "{title=Breakfast, category=FOOD}",
      "{title=Wine Bar, category=FOOD}",
      "{title=Coffee, category=FOOD}"
    ]
  }
};

print(Activities.fromJson(json));
```

build.yaml looks like so:
```
targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/src/domains/**/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/src/domains/**/*.dart
        options:
          any_map: true
          explicit_to_json: true
```

Thanks, any help would be greatly appreciated.
