### ISSUE TITLE
Use null-safety `build` dependency

### ISSUE THREAD

**Issue by jarekb123** [rrousselGit/freezed#391]
**Describe the bug**
```
pubspec.yaml

dependecies:
  freezed_annotation: ^0.14.0

dev_dependencies:
  freezed: ^0.14.0+1
  build_runner: ^1.12.0
```

I can't use freezed along with packages that depends on `build 2.0`, like `build_runner 1.12.0`.

**Expected behavior**

It is possible to use packages that uses null-safety `build` dependency.

**Comment by rrousselGit** [comment]
This is blocked by [source_gen](https://pub.dev/packages/source_gen)

**Comment by mwenechac** [comment]
build_runner: ^1.10.3 worked for me with freezed: ^0.14.1 & freezed: ^0.14.1

**Comment by passsy** [comment]
source_gen tracking issue https://github.com/dart-lang/source_gen/issues/493

**Comment by rrousselGit** [comment]
Ironically the issue is closed, but the null-safe version hasn't been
published yet

Le lun. 15 mars 2021 à 19:13, Pascal Welsch ***@***.***> a
écrit :

**Comment by simolus3** [comment]
`source_gen` hasn't migrated to null safety yet, but there's a published version of `source_gen` with support for the latest build packages. If you're not using `AssetId.resolve`, you can probably just increase your `build` dependency constraints to `<3.0.0`.

**Comment by oscarshaitan** [comment]
https://github.com/dart-lang/source_gen/pull/517 
is upgraded now !!

**Comment by yakou32** [comment]
I'm sorry, but I don't get how to fix this issue...

```
dependencies:
  freezed_annotation: ^0.14.1

dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.1+1
```

I get this error on build:
```
This builder requires Dart inputs without syntax errors.
However, [package] (or an existing part) contains the following errors.
Unexpected text 'required'.
This requires the 'non-nullable' language feature to be enabled
```
`dart pub outdated --mode=null-safety` shows that `build_runner` doesn't have any version with null-safety support.

I was following the readme, but I can't find how to use the latest null-safety version of freezed...

Thanks :)
