### ISSUE TITLE
null safety version generating incorrect types

### ISSUE THREAD

**Issue by britannio** [rrousselGit/freezed#399]
**Describe the bug**
The current null safe version of Freezed is generating properties with the `dynamic` type instead of the specified type.

**To Reproduce**
a.dart
```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'b.dart';
part 'a.freezed.dart';

@freezed
class A with _$A {
  const factory A({required BImpl? b}) = _A;
}
```

b.dart
```dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'b.freezed.dart';

@freezed
class B with _$B {
  const factory B() = BImpl;
}
```

a.freezed.dart
https://gist.github.com/britannio/3c96b694aa79b1bac09756c9b2b80386

b.freezed.dart (less relevant)
https://gist.github.com/britannio/9b7005aff2cae9ce37f8a7e2aed6a498

**Expected behaviour**
Lines 19, 31, 40, 59, 69, 96, 121 and 124 of a.freezed.dart should use the correct type (`BImpl` in this case) instead of dynamic.

pubspec.lock
```
  freezed:
    dependency: "direct dev"
    description:
      name: freezed
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.1"
  freezed_annotation:
    dependency: "direct main"
    description:
      name: freezed_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.1"
```
