### ISSUE TITLE
fromJson and to Json are not properly generated

### ISSUE THREAD

**Issue by yakou32** [rrousselGit/freezed#407]
I use the sample from the readme:

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';
part 'model.g.dart';

@freezed
class Model with _$Model {
  factory Model.first(String a) = First;
  factory Model.second(int b, bool c) = Second;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```
Code is generated with `flutter pub run build_runner build --delete-conflicting-outputs`

I get the following errors:

- in `model.dart`: `Target of URI hasn't be generated: 'model.g.dart'.`
- in `model.freezed.dart`: 
    - `factory _$First.fromJson(Map<String, dynamic> json) => _$_$FirstFromJson(json);` The method `_$_$FirstFromJson` isn't defined for the type `_$First`.
    - `return _$_$FirstToJson(this)..['runtimeType'] = 'first';` The method `_$_$FirstToJson` isn't defined for the type `_$First`.
    - (the same for Second)

I suppose that the generated code should not present these errors.

Pubspec:
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.14.1

dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.1+1
```

Thanks for the help :)
