### ISSUE TITLE
Supporting List of non primitive types in toJson

### ISSUE THREAD

**Issue by Igos19** [rrousselGit/freezed#42]
Hi,

There's a problem when using property List of generated items, toJson method works incorrect.

```kotlin
@immutable
abstract class VideoModel with _$VideoModel {
  const factory VideoModel({@JsonKey(name: 'id') String id,
    @JsonKey(name: 'iso_639_1') String iso639,
    @JsonKey(name: 'iso_3166_1') String iso3166,
    @JsonKey(name: 'key') String key,
    @JsonKey(name: 'name') String name,
    @JsonKey(name: 'site') String site,
    @JsonKey(name: 'size') int size,
    @JsonKey(name: 'type') String type}) = _VideoModel;

  factory VideoModel.fromJson(Map<String, dynamic> json) =>
      _$VideoModelFromJson(json);
}

@immutable
abstract class DataVideosModel with _$DataVideosModel {
  const factory DataVideosModel(
      {@JsonKey(name: 'results') List<VideoModel> results,
        @JsonKey(name: 'id') int id}) = _DataVideosModel;

  factory DataVideosModel.fromJson(Map<String, dynamic> json) =>
      _$DataVideosModelFromJson(json);
}
```

Currently toJson method is generated like:

```kotlin
Map<String, dynamic> _$_$_DataVideosModelToJson(_$_DataVideosModel instance) =>
    <String, dynamic>{
      'results': instance.results,
      'id': instance.id,
    };
```

Could you make supporting List in toJson method like this: (in that cases when List isn't List of primivite types)

```kotlin
Map<String, dynamic> _$_$_DataVideosModelToJson(_$_DataVideosModel instance) =>
    <String, dynamic>{
      'results': instance.results.map((result) => result.toJson()),
      'id': instance.id,
    };
```

**Comment by rrousselGit** [comment]
Hi!
That's the job of json_serializable, not freezed. 

Freezed is merely delegating that part to json_serializable. 
Consider making an issue on their repository

**Comment by knaeckeKami** [comment]
Just as hint for anybody that also runs into this:
this is supported by json_serializable, but has to be enabled, either per class or globally via the
explicit_to_json flag in the build.yaml file.

Example:

```
@freezed
@JsonSerializable(explicitToJson: true)
abstract class MyModel with _$Model{ ... }
```


```
targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/model/**
            - lib/feature/**/model/*.dart
            - lib/api/**
          exclude:
            - lib/api/grapql_authentication_link.dart
            - lib/api/timeout_client.dart
            - lib/api/plexus/plexus_client.dart
            - lib/api/plexus/absinthe_file_upload_link.dart
            - lib/api/phoenix/phoenix_api.dart
            - lib/api/cerebro/ifap/request/smpc_request.dart
      built_value_generator:built_value:
        generate_for:
          include:
            - lib/model/app_state.dart
            - lib/feature/**/model/*.dart
            - lib/api/serializers.dart
            - lib/api/phoenix/**/*.dart
      # should be same as built_value!
      json_serializable:json_serializable:
        options:
          explicit_to_json: true
```
