### ISSUE TITLE
Nullable variables are not generated as non-null variables.

### ISSUE THREAD

**Issue by TheHemantKaushik** [rrousselGit/freezed#440]
**Describe the bug**
I am trying to generate code of a model contains `DateTime` variables with null and non-null types. Generated code is different for both. 

* when both fields are same, output is:
```
    start: timestampConverter.fromJson(json['start'] as Timestamp),
    end: timestampConverter.fromJson(json['end'] as Timestamp)
```
* when a field is null, output is:
```
    start: timestampConverter.fromJson(json['start'] as Timestamp),
    end: json['end'] == null ? null : DateTime.parse(json['end'] as String),
```

**To Reproduce**

__pubspec.yaml__
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  freezed_annotation:

dev_dependencies:
  freezed:
  build_runner:
  json_serializable:
```

__models.dart__
```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
part 'models.freezed.dart';
part 'models.g.dart';

class TimestampConverter implements JsonConverter<DateTime, Timestamp> {
  const TimestampConverter();
  @override
  DateTime fromJson(Timestamp timestamp) => timestamp.toDate();
  @override
  Timestamp toJson(DateTime date) => Timestamp.fromDate(date);
}

@freezed
class TimeLogModel with _$TimeLogModel {
  TimeLogModel._();

  factory TimeLogModel({
    required String id,
    @TimestampConverter() required DateTime start,
    @TimestampConverter() required DateTime end,
  }) = _TimeLogModel;

  factory TimeLogModel.fromJson(Map<String, dynamic> json) =>
      _$TimeLogModelFromJson(json);
}
```

**Change it to `end` field to nullable field and check difference in `models.g.dart`**
    

**Expected behavior**
Nullable fields should be generated as non-null fields.
