### ISSUE TITLE
Using json_serializable  v5 causes invalid_annotation_target warnings

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/freezed#488]
Example:

```dart
@freezed
class Example with _$Example {
  factory Example(
    @JsonKey() // invalid_annotation_target
    String value,
  ) = _Example
}
```

**Comment by rrousselGit** [comment]
For now my recommendation would be to disable this warning. Such as with:

```yaml
# analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
```
