### ISSUE TITLE
Ignore all lints in generated files

### ISSUE THREAD

**Issue by hacker1024** [rrousselGit/freezed#571]
**Is your feature request related to a problem? Please describe.**
At the moment, generated files ignore a specific set of lints. This list needs to be continuously updated as new lints are added, and does not cover lints added by analyser plugins.

**Describe the solution you'd like**
Dart 2.15 adds a new ignore directive to ignore all lints in a file:

```dart
// ignore_for_file: type=lint
```

This can be used to ignore all lints, instead of a specific set.

**Describe alternatives you've considered**
Generated files can also be excluded from analysis, but this is inconvenient as it breaks auto-completion and most other IDE niceties.

**Additional context**

**Comment by hacker1024** [comment]
Also - for generators like json_serializable that output to the combined `.g.dart` files, the following can be done in `build.yaml`:

```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
```
