### ISSUE TITLE
Build script fails in newly generated project

### ISSUE THREAD

**Issue by vmorilla** [rrousselGit/freezed#584]
**Describe the bug**
Freezed fails on a newly generated flutter project producing the following errors:
```
[SEVERE] freezed:freezed on test/widget_test.dart (cached):

/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:2865:12 - The name of a constructor must match the name of the enclos:pub finished with exit code 1
ing class.
/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3031:3 - Can't have modifier 'static' here.
/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:2965:3 - Can't have modifier 'static' here.
/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3075:3 - Can't have modifier 'static' here.
/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3114:1 - Expected a method, getter, setter or operator declaration.
/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3096:3 - Can't have modifier 'static' here.
/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:2868:3 - Can't have modifier 'static' here.
/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:2865:5 - Expected a class member.
/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:2903:3 - Can't have modifier 'static' here.
/Users/vmorilla/devel/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3009:3 - Can't have modifier 'static' here.
```

**To Reproduce**
```bash
flutter create new_project
# add dependencies pubspec.yaml (see below)
cd new_project
flutter pub get
flutter pub run build_runner build
```

pubspec.yaml
```yaml

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  flutter_lints: ^1.0.0
```

**Expected behavior**
No errors :)
