### ISSUE TITLE
Interdependency issue between freezed and envify

### ISSUE THREAD

**Issue by dorsamet** [rrousselGit/freezed#596]
**Describe the bug**
Freezed isn't compatible with envify
**To Reproduce**
Add the following to the pubspec.yaml file:

```
dependencies:
    envify: any
    freezed: 

dev_dependencies:
    envify_generator: any
    freezed_annotation:
```
Run `flutter pub get`

**Expected behavior**
Dependencies are downloaded, and everything works

**Actual result**
`Because envify_generator <2.0.0 depends on source_gen ^0.9.7+1 and envify_generator >=2.0.0 <2.0.1 depends on analyzer ^1.2.0, envify_generator <2.0.1 requires source_gen ^0.9.7+1 or analyzer ^1.2.0.
And because envify_generator >=2.0.1 depends on analyzer ^2.0.0, every version of envify_generator requires analyzer ^1.2.0 or ^2.0.0 or source_gen ^0.9.7+1.
And because freezed 1.1.1 depends on both analyzer ^3.0.0 and source_gen ^1.2.0, envify_generator is incompatible with freezed 1.1.1.
Because every version of core from path depends on freezed ^1.1.1 and no versions of freezed match >1.1.1 <2.0.0, every version of core from path requires freezed 1.1.1.`

Where `core` is a local module/package
