### ISSUE TITLE
`build.yaml`'s `ignore_for_file` does not work for `freezed`

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/freezed#606]
Hi thanks for the lib! I see lots of warnings like: `info: Avoid overloading operator == and hashCode on classes not marked `@immutable`. (avoid_equals_and_hash_code_on_mutable_classes at [...] ...freezed.dart:147)`. I do not want to use `analysis_options.yaml` to ignore *the whole file* from linter, neither do I want to ignore the *whole lint rule* for every file in the package. So I choose to change `build.yaml` as follows:

```
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - non_constant_identifier_names
            - duplicate_ignore
            - invalid_annotation_target
            - avoid_equals_and_hash_code_on_mutable_classes
```

And then `flutter pub run build_runner watch --delete-conflicting-outputs --verbose`

However, this lib does not seem to understand it. The generated code looks like:

```
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target

part of 'container_span_builder_base.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more informations: https://github.com/rrousselGit/freezed#custom-getters-and-methods');

...
```
```

So I wonder how can `freezed` respect this? Thanks!
