### ISSUE TITLE
How to use with package specified as git dependency in pubspec.yaml

### ISSUE THREAD

**Issue by nightscape** [rrousselGit/freezed#631]
I wrote a [Dart library](https://github.com/nightscape/stream_graph.dart) that uses freezed to generate a few classes. In a Flutter app I'm using this library as a Git dependency, as the package is not yet published:
```yaml
dependencies:
  stream_graph:
    git:
      url: https://github.com/nightscape/stream_graph.dart.git
```

As specified in the [`build_runner` docs](https://pub.dev/packages/build_runner#source-control) I didn't put the generated `.freezed.dart` files into version control.
Now in the Flutter app, it seems as if `build_runner` is not generating the `.freezed.dart` files for the library.
This is not surprising, but after quite a bit of research, I haven't found a recommended way to handle this situation.

I'm aware that this is not necessarily freezed specific, but I'm wondering if anybody has run into this problem before, and if there's maybe an easy and obvious solution that I just keep missing.

Thanks a lot!
