### ISSUE TITLE
build.yaml custom output directory

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/freezed#632]
I currently have
```yaml
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generated/{{}}.g.dart'
```
In my `build.yaml` to make my codebase cleaner as I work in it. however, Freezed does not respect this option, and I cant find a way to achieve the same thing.

I propose a new option for the builder to change the location of `.freezed.dart` files to work exactly the same as the above setting.

It would really help with readability and organization.

**Comment by rrousselGit** [comment]
I don't mind, but I personally won't work on this.

Happy to review a pull request though.

**Comment by TekExplorer** [comment]
Actually, I figured out how to make it work. not sure why it didn't work before, but hey.

Good to add to the documentation though @rrousselGit!

```YAML
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generated/{{}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generated/{{}}.freezed.dart'
```
