### ISSUE TITLE
Add build.yaml `build_extensions` option to docs to show how to move generated files.

### ISSUE THREAD

**Issue by TekExplorer** [rrousselGit/freezed#633]
I got kind of annoyed with the swarm of files I was gathering and had discovered the first part of this snippet.

However, I had wanted to do the same for `freezed` and could not figure out how.

Perhaps add this snippet (or similar) to the docs. to show how to de-clutter one's project
`build.yaml`
```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generated/{{}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generated/{{}}.freezed.dart'
```

**Comment by rrousselGit** [comment]
Your issue should be good enough as documentation already


I don't think having it as part of the Readme is necessary considering that's fairly advanced and rare.

**Comment by TekExplorer** [comment]
Well, I suppose that's my job done then, eh?

Idk, I think more people would do this if they knew about it.

You don't have to add the snippet directly, but you could probably include a line like
"If you want to move all generated files to their own folder, refer to <link to this issue>" or something

**Comment by rrousselGit** [comment]
It's not really Freezed specific though. It's probably more docs about build_runner

**Comment by TekExplorer** [comment]
Well, I suppose it doesn't really matter. As you said, anyone that wants to do this can now find out how through this issue 👍

**Comment by Kiruel** [comment]
I just put the link to `build_runner` doc: https://github.com/dart-lang/source_gen/blob/master/source_gen/README.md#generating-files-in-different-directories 
For more details.

**Comment by orevial** [comment]
Are you sure it's not worth it mentioning in the doc ?
I think it's actually a pretty recurring topic (this issue, #632, #553, #106) and the information is kind of hard to find.

In the meantime I'll also add an example to generate outputs in a `generated/` directory at the same hierarchy level as the source file : 

`build.yaml` :

```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/generated/{{file}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/generated/{{file}}.freezed.dart'
```

It uses multiple capture groups as described in [Using multiple capture groups](https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md#using-multiple-capture-groups) from official doc.
