### ISSUE TITLE
makeCollectionsUnmodifiable build.yaml option uneffective

### ISSUE THREAD

**Issue by Maatteogekko** [rrousselGit/freezed#651]
**Describe the bug**

Just upgraded to feezed 2.0.2 and need to keep the mutable Lists, Maps and Sets.
I specified the option in the `build.yaml`, but it does not work.
My build.yaml:
```yaml
targets:
  $default:
    builders:
      freezed:
        options:
          makeCollectionsUnmodifiable: false
```

**To Reproduce**

[Here](https://github.com/Maatteogekko/freezed_issue) is a minimal app with two freezed classes. and the `build.yaml` specified above.
`Model` generates code with unmodiable list, while `ModelUnmodifiable` which has  `makeCollectionsUnmodifiable: false` explicitly set, generates code with modifiable lists.

**Expected behavior**

I expected that `Model` generated code would enable modifiable lists, since I set the option globally in the `build.yaml`.
