### ISSUE TITLE
Disabling map and/or when generation from build.yaml is not working

### ISSUE THREAD

**Issue by KlausJokisuo** [rrousselGit/freezed#661]
**Describe the bug**
Disabling map and/or when generation from the build.yaml is not working

Note: `@Freezed(map: FreezedMapOptions(maybeMap: false))` works fine.

**To Reproduce**

test.dart

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test.freezed.dart';

@Freezed()
class Test with _$Test {
  const factory Test.initial({required String test}) = Initial;
  const factory Test.something({required String test}) = Something;
}

```

build.yaml
```
targets:
  $default:
    builders:
      freezed:
        options:
          maybe_map: false
          maybe_when: false


```

**Expected behavior**
when & map methods should not be generated when disabled from the build.yaml

**Comment by rrousselGit** [comment]
The syntax is:

```
targets:
  $default:
    builders:
      freezed:
        options:
          map:
            maybe_map: false
```

**Comment by KlausJokisuo** [comment]
> targets:
>   $default:
>     builders:
>       freezed:
>         options:
>           map:
>             maybe_map: false

I actually tested that before but I get this error:

```
[SEVERE] 
type 'YamlMap' is not a subtype of type 'Map<String, dynamic>' in type cast
[INFO] Terminating. No further builds will be scheduled

[INFO] Builds finished. Safe to exit
```

**Comment by rupinderjeet** [comment]
Reproducible with following `build.yaml`

```
targets:
  $default:
    builders:

      # https://github.com/rrousselGit/freezed#changing-the-behavior-for-the-entire-project
      freezed:
        options:
          map:
            map: false
            map_or_null: false
            maybe_map: false
          when:
            when: false
            when_or_null: false
            maybe_when: false
```
