### ISSUE TITLE
The method '_$$_PersonFromJson' isn't defined for the type '_$_Person'.

### ISSUE THREAD

**Issue by bettersun** [rrousselGit/freezed#666]
**Describe the bug**

Error message:
The method '\_$$\_PersonFromJson' isn't defined for the type '_$_Person'.

**To Reproduce**

$ flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[!] HTTP Host Availability
    ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error
      occurred while checking the HTTP host: Operation timed out

! Doctor found issues in 1 category.
```

pubspec.yaml
```
dependencies:   
    freezed: ^2.0.3   
    freezed_annotation: ^2.0.3   
dev_dependencies:   
    build_runner: ^2.1.10   
```

person.dart
```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'person.freezed.dart';

@freezed
class Person with _$Person {
  const factory Person({
    required String firstName,
    required String lastName,
    required int age,
  }) = _Person;

  factory Person.fromJson(Map<String, Object?> json) => _$PersonFromJson(json);
}
```

run 'flutter pub run build_runner build'

**Expected behavior**

There should be no errors.

**Comment by SunlightBro** [comment]
Please check the [FromJson/ToJson](https://github.com/rrousselGit/freezed#fromjsontojson) section in the Readme.

In your **person.dart** file you are missing:
```dart
part 'person.g.dart';
```
And also check your **pubspec.yaml**:
```YAML
dependencies:
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.3
  json_serializable: ^6.2.0
```
