### ISSUE TITLE
Freezed doesn't respect global JsonSerializable's createToJson

### ISSUE THREAD

**Issue by AlexanderFarkas** [rrousselGit/freezed#779]
**Describe the bug**
Freezed created toJson methods even if create_to_json is disabled in build.yaml:
```yaml
targets:
  $default:
    builders:
      json_serializable: #Replacing `json_serializable` with `freezed` doesn't make any difference
        options:
          create_to_json: false
```

**To Reproduce**

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'fixture.freezed.dart';
part 'fixture.g.dart';

@freezed
class Fixture with _$Fixture {
  const factory Fixture({
    required int id,
    }) = _Fixture;
    
    factory Fixture.fromJson(Map<String, dynamic> json) => _$FixtureFromJson(json);
 }
```

Run build_runner, open `fixture.freezed.dart`:
```dart
The method '_$$_FixtureToJson' isn't defined for the type '_$_Fixture'.
Try correcting the name to the name of an existing method, or defining a method named '_$$_FixtureToJson'
```

**Expected behavior**
Freezed should either respect global setting or provide its own. (How it does with `genericArgumentFactories`)
