### ISSUE TITLE
Generic arguments with JsonSerializable and global config

### ISSUE THREAD

**Issue by AlexanderFarkas** [rrousselGit/freezed#780]
**Describe the bug**

My `build.yaml`:
```yaml
targets:
  $default:
    builders:
      freezed:
        options:
          generic_argument_factories: true
          to_json: false

```

In that case it works only if fromJson is an arrow function:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'data.freezed.dart';
part 'data.g.dart';

@Freezed(genericArgumentFactories: true)
class Data<T> with _$Data<T> {
  const factory Data({
    required T data,
  }) = _Data<T>;

  factory Data.fromJson(Map<String, dynamic> json, T Function(Object?) fromJsonT) => _$DataFromJson(json, fromJsonT);
}
```

Also, this code produces build_runner error, though   `generic_argument_factories: true` defined globally:
```dart 
import 'package:freezed_annotation/freezed_annotation.dart';

part 'data.freezed.dart';
part 'data.g.dart';

@freezed
class Data<T> with _$Data<T> {
  const factory Data({
    required T data,
  }) = _Data<T>;

  factory Data.fromJson(Map<String, dynamic> json, T Function(Object?) fromJsonT) => _$DataFromJson(json, fromJsonT);
}
```
