### ISSUE TITLE
Unable to implement a base class

### ISSUE THREAD

**Issue by fennelhans** [rrousselGit/freezed#869]
**Describe the bug**
I am unable to specify a base class with common parameters. In this example, I want both `Armor` and `Weapon` to be `Equipment` and I should be able to specify a `name` for either of them. Either I'm going insane, or Freezed doesn't support this.

**To Reproduce**

lib/freezed_test.dart:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'freezed_test.freezed.dart';
part 'freezed_test.g.dart';

@freezed
class Armor with _$Armor implements Equipment {
  const factory Armor({
    int? ac,
  }) = _Armor;

  factory Armor.fromJson(Map<String, dynamic> json) => _$ArmorFromJson(json);
}

abstract class Equipment {
  final String? name;
  const Equipment({this.name});
}

@freezed
class Weapon with _$Weapon implements Equipment {
  const factory Weapon({
    int? damage,
  }) = _Weapon;

  factory Weapon.fromJson(Map<String, dynamic> json) => _$WeaponFromJson(json);
}
```

bin/freezed_test.dart:

```dart
import 'dart:convert';

import 'package:freezed_test/freezed_test.dart';

void main() {
  final Armor armor = Armor(name: "Test Armor", ac: 10);
  final Armor armor2 =
      Armor.fromJson(jsonDecode('{name: "Test Armor 2", ac: 10}'));

  final Weapon weapon = Weapon(name: "Test Weapon", damage: 100);

  print(armor.name);
  print(armor2.name);
  print(weapon.name);
}
```

pubspec.yaml:

```yaml
name: freezed_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  # path: ^1.8.0
  freezed_annotation: ^2.2.0
  equatable: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  build_runner: ^2.3.0
```

I have also tried something like this:

```dart
@freezed
class Armor with _$Armor {
  @Implements<Equipment>()
  const factory Armor({
    int? ac,
  }) = _Armor;

  factory Armor.fromJson(Map<String, dynamic> json) => _$ArmorFromJson(json);
}
```

**Expected behavior**
Both `Armor` and `Weapon` should allow me to specify a `name` parameter, as defined in the parent class, `Equipment`.
