### ISSUE TITLE
Boolean values for when and map options not working

### ISSUE THREAD

**Issue by MicTheFox** [rrousselGit/freezed#946]
**Describe the bug**
The `map` or `when` options don't accept a boolean value. Using a map works fine.

The error looks like this: 
`type 'bool' is not a subtype of type 'Map<dynamic, dynamic>' in type cast`

My guess is that the changes of PR #944 need to be released in the `json_annotation` package.

**To Reproduce**

Create a `build.yaml` with the following content:

```
targets:
  $default:
    builders:
      freezed:
        options:
          when: false
```

A minimal `pubspec.yaml` looks like this:

```
name: test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.0
```

**Expected behavior**
The build runner should run without an exception.
