### ISSUE TITLE
[genericArgumentFactories: true] Not working

### ISSUE THREAD

**Issue by ziqq** [rrousselGit/freezed#949]
**Describe the bug**

I can't generate with dynamic params and i can't get FromJson<T>.

**To Reproduce**
<details>
  <summary>select_item_dynamic_model.codegen.dart</summary>

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'select_item_dynamic_model.codegen.g.dart';
part 'select_item_dynamic_model.codegen.freezed.dart';

@Freezed(genericArgumentFactories: true)
class MSelectItemDynamic<T> with _$MSelectItemDynamic<T> {
  const MSelectItemDynamic._();

  factory MSelectItemDynamic({
    required String text,
    required T value,
  }) = _MSelectItemDynamic;

  factory MSelectItemDynamic.fromJson(
    JSON json,
    T Function(Object? json) fromJsonT,
  ) {
    return _$MSelectItemDynamicFromJson<T>(json, fromJsonT);
  }
}
```
</details>

<details>
  <summary>build.yaml</summary>
 
```yaml
targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          exclude:
            - 'example/**'
          include:
            - lib/**.codegen.dart
        options:
          explicit_to_json: true
          # field_rename: snake
      freezed:
        options:
          explicit_to_json: true
          # generic_argument_factories: true
        generate_for:
          exclude:
            - 'example/**'
          include:
            - lib/**.codegen.dart
```
</details>
